# Write your MySQL query statement below
WITH CTE AS(
SELECT REQUESTER_ID AS ID
FROM REQUESTACCEPTED 
UNION ALL
SELECT ACCEPTER_ID AS ID
FROM REQUESTACCEPTED
)

SELECT ID,COUNT(*) AS num 
FROM CTE
GROUP BY ID
ORDER BY num DESC
limit 1;