# Write your MySQL query statement below
WITH DUMMY AS(
SELECT D.NAME AS DEPARTMENT,E.NAME AS EMPLOYEE,E.SALARY AS SALARY,
DENSE_RANK() OVER(PARTITION BY D.id ORDER BY E.SALARY DESC) AS ranking
FROM EMPLOYEE E JOIN DEPARTMENT D ON E.departmentId=D.id
)
SELECT DEPARTMENT,EMPLOYEE,SALARY FROM DUMMY
WHERE ranking<4;

